#
# Copyright (C) 2019-2024, HENSOLDT Cyber GmbH
# 
# SPDX-License-Identifier: GPL-2.0-or-later
#
# For commercial licensing, contact: info.cyber@hensoldt.net
#

#-------------------------------------------------------------------------------
# A temporary layer used only for building customized QEMU.
# Existing QEMU binaries can be imported by replacing following code by
# FROM --platform=${TARGETPLATFORM} trentos_build:<tag> as qemu_build

FROM ubuntu:focal as qemu_build

ADD install-package.tgz /tmp/install-scripts/
RUN cd /tmp/install-scripts \
    && ./install-qemu-build.sh

#-------------------------------------------------------------------------------
# Main layer used to build the build container.
FROM trustworthysystems/camkes:2023_06_12 as trentos_build

LABEL MAINTAINER="info.cyber@hensoldt.net"
LABEL ORGANISATION="HENSOLDT Cyber GmbH"

ARG USER_NAME
ARG USER_ID

# Copy archive contents into container and run installer script.
# trustworthysystems/camkes has scripts in /tmp, so we can't remove all content
# there as a clean-up step.
ADD install-package.tgz /tmp/install-scripts/
RUN cd /tmp/install-scripts \
    && ./install-script.sh ${USER_ID} ${USER_NAME} \
    && rm -rf /tmp/install-scripts /var/tmp/*

# Copy custom QEMU-build.
# Existing QEMU binaries can be imported from the trentos_build base-layer by:
# COPY --from=qemu_build /opt/hc/bin /opt/hc/bin
COPY --from=qemu_build /tmp/bin /opt/hc/bin
ENV PATH="$PATH:/opt/hc/bin"

USER ${USER_NAME}

ENTRYPOINT ["/entrypoint.sh"]

CMD ["bash"]
