#-------------------------------------------------------------------------------
# A temporary layer used only for building customized QEMU.
# Existing QEMU binaries can be imported by replacing following code by
# FROM --platform=${TARGETPLATFORM} trentos_test:<tag> as qemu_build

#
# Copyright (C) 2019-2024, HENSOLDT Cyber GmbH
# 
# SPDX-License-Identifier: GPL-2.0-or-later
#
# For commercial licensing, contact: info.cyber@hensoldt.net
#

FROM ubuntu:focal as qemu_build

ADD install-package.tgz /tmp/install-scripts/
RUN cd /tmp/install-scripts \
    && ./install-qemu-build.sh

#-------------------------------------------------------------------------------
# Main layer used to build the test container.
FROM ubuntu:focal as trentos_test

LABEL MAINTAINER="info.cyber@hensoldt.net"
LABEL ORGANISATION="HENSOLDT Cyber GmbH"

ARG USER_NAME
ARG USER_ID

# Copy archive contents into container and run installer script.
ADD install-package.tgz /tmp/install-scripts/
RUN cd /tmp/install-scripts \
    && ./install-script.sh ${USER_ID} ${USER_NAME} \
    && rm -rf /tmp/* /var/tmp/*

# Copy custom QEMU-build.
# Existing QEMU binaries can be imported from the trentos_build base-layer by:
# COPY --from=qemu_build /opt/hc/bin /opt/hc/bin
COPY --from=qemu_build /tmp/bin /opt/hc/bin
ENV PATH="$PATH:/opt/hc/bin"

USER ${USER_NAME}

ENTRYPOINT ["/entrypoint.sh"]

CMD ["bash"]
