#
# Copyright (C) 2019-2024, HENSOLDT Cyber GmbH
# 
# SPDX-License-Identifier: GPL-2.0-or-later
#
# For commercial licensing, contact: info.cyber@hensoldt.net
#

FROM ubuntu:focal

LABEL MAINTAINER="info.cyber@hensoldt.net"
LABEL ORGANISATION="HENSOLDT Cyber GmbH"

ARG USER_NAME
ARG USER_ID

# Copy archive contents into container and run installer script.
ADD install-package.tgz /tmp/install-scripts/
RUN cd /tmp/install-scripts \
    && ./install-script.sh ${USER_ID} ${USER_NAME} \
    && rm -rf /tmp/* /var/tmp/*

USER ${USER_NAME}

ENTRYPOINT ["/entrypoint.sh"]

CMD ["bash"]
